# Generated by Django 6.0.4 on 2026-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0002_alter_fuelstation_retail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(blank=True, max_length=128)),
                ('origin_state', models.CharField(db_index=True, max_length=2)),
                ('dest_city', models.CharField(blank=True, max_length=128)),
                ('dest_state', models.CharField(db_index=True, max_length=2)),
                ('equipment_type', models.CharField(choices=[('dry_van', 'Dry Van'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed')], db_index=True, max_length=16)),
                ('rate_per_mile', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['origin_state', 'dest_state', 'equipment_type'], name='lane_rate_lane_idx')],
            },
        ),
    ]
